name: linux

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        cvmfs_base: ['sft.cern.ch/lcg/views']
        ENVIRONMENT: ['LCG_102rc1/x86_64-centos7-gcc11-opt',
                      'dev3/latest/x86_64-centos7-gcc10-opt',
                      ]
        include:
        - cvmfs_base: 'sw.hsf.org'
          ENVIRONMENT: 'key4hep'
        - cvmfs_base: 'sw-nightlies.hsf.org'
          ENVIRONMENT: 'key4hep'
    steps:
    - uses: actions/checkout@v2
    - uses: cvmfs-contrib/github-action-cvmfs@v2
    - name: Start container
      run: |
        docker run -it --name CI_container -v ${GITHUB_WORKSPACE}:/Package -v /cvmfs:/cvmfs:shared -d ghcr.io/aidasoft/centos7:latest /bin/bash
    - name: CMake Configure
      run: |
         docker exec CI_container /bin/bash -c 'cd Package;\
         mkdir -p build install;\
         source /cvmfs/${{ matrix.cvmfs_base }}/${{ matrix.ENVIRONMENT }}/setup.sh;\
         cd build;\
         cmake -DCMAKE_INSTALL_PREFIX=../install -DCMAKE_CXX_STANDARD=17  -DCMAKE_CXX_FLAGS=" -fdiagnostics-color=always " -G Ninja ..;'
    - name: Compile
      run: |
        docker exec CI_container /bin/bash -c 'cd ./Package;\
        source /cvmfs/${{ matrix.cvmfs_base }}/${{ matrix.ENVIRONMENT }}/setup.sh;\
        cd build;\
        ninja -k0;'
    - name: Test
      run: |
        docker exec CI_container /bin/bash -c 'cd ./Package;\
        source /cvmfs/${{ matrix.cvmfs_base }}/${{ matrix.ENVIRONMENT }}/setup.sh;\
        cd build;\
        ninja -k0 && ctest --output-on-failure;'
    - name: Install
      run: |
        docker exec CI_container /bin/bash -c 'cd ./Package;\
        source /cvmfs/${{ matrix.cvmfs_base }}/${{ matrix.ENVIRONMENT }}/setup.sh;\
        cd build;\
        ninja -k0 install;'
